name: Shippy

on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - synchronize
  workflow_dispatch:
    # NOTE: To prevent GitHub from adding PRs to the merge queue before check is done,
    # make sure that there is a ruleset that requires the “Shippy check to pass.
    merge_group:
      types:
        - checks_requested
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-pr-description:
    name: PR Description Check
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - name: Check PR description
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body?.trim()
            if (!prBody) {
              core.setFailed("❌ PR description is required.")
            }
